[package]
name = "rustcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.2"

[dependencies.xxhash-rust]
version = "0.8.5"
features = ["xxh3"]

[profile.release]
strip = true
lto = true
